### ISSUE TITLE
Dataset page: chart preview error

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1005]
### Problem description
I see a "Loading chunk 1 failed." error for the chart visualisation. 
If the chart doesn't show, hide this tab altogether.

### Problem reproduction steps
http://magda-dev.terria.io/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details?q=#chart

### Screenshot / Design / File reference
<img width="312" alt="screen shot 2018-05-18 at 2 32 23 pm" src="https://user-images.githubusercontent.com/2201814/40216180-6951a2ec-5aa8-11e8-9567-a5d35956465f.png">

**Comment by t83714** [comment]
Error means the data file (the remote CSV file) can't be downloaded probably.
This happens after 
- we determined the data file is viewable (i.e. link not broken).
- Chart tab is created and shown
- Loading box is shown
Probably too late to hide the chart tab.
Also, it's more likely a network issue --- that's something wrong with user's internet or remote server.
That's why the link is working OK now.

**Comment by AlexGilleran** [comment]
Underlying issue works ok now - have created a separate one for the other part of this (hiding the chart tab on error): https://github.com/magda-io/magda/issues/1396
