### ISSUE TITLE
UX: Map preview zoom functionality

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1182]
### Problem description
Users are accidentally zooming on on the map when they mean to scroll down the website. 
- [ ] Introduce zoom in/zoom out buttons for the map
- [ ] Introduce a reset option

**Comment by philipgrimmett** [comment]
**Proposed solution**

Adopt NationalMap approach of providing a limited zoom-toggle map preview (see video). If the intent is to give visitors a rough idea of the scale and location of data, this approach should help be sufficient and provides incentive to move through to the national map (instead of scrambling around in a tiny viewport)

https://drive.google.com/file/d/1ODlhs6bY2t9vQyszjisZBfbFXEPTy7pP/view?usp=sharing
