### ISSUE TITLE
Simplify the secrets

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1403]
### Description

As a Magda maintainer
I want to be able to enter all credentials in one go
So that I can install Magda quickly

### Acceptance criteria:
- Only one k8s secret for all passwords
- Update installation guide to have only one line to setup secrets
- The installer should work with one secret

**Comment by t83714** [comment]
@AlexGilleran 
Have a look at current setup script and created a list of secrets (see table below. also **[shared link](https://docs.google.com/spreadsheets/d/1dGIMiwYQ5j19Wu8VPi-6Sv5EZAXfAnf5hWHqyYPEiug/edit?usp=sharing)**) that is required to create (depends on envoriment. i.e. preview site, dev site or production site) before a Magda cluster can run on k8s.  (Please add more to the list if I missed any secrets)

Some secrets can be auto generated without extra information from the user. Some need extra information from user (e.g. password or keys) before we can create secrets config in k8s. 

Therefore, I guess the final deliverable for this issue could be an better version of `create-auth-secrets.sh` script which can:
- Ask user's situation to decide which secrets are required for user's setup
  - e.g. if user doesn't use google cloud SQL database, then the script will not attempt to create `cloudsql-instance-credentials`
- Auto create random internal credentials that doesn't require user's input
- Should be able to capture credentials information from either user input or envoriment variable (therefore, it can be used for possible automation script as well)
- Should be able to work under two modes
  - Interaction Mode: Ask user to input all required credentials for secrets creation
  - Automated / Slient Mode: Look for all required credentials from envoriment variable 

So, I guess the benefit of having this tool would be:
- Hide some technical details from users. Reduce technical skills required for users to setup their own magda instance
- Minimise the risk of missing secrets. So, users are less likely to stuck somewhere just because he forgot to create one secret.

@aneesha09 Please let me know if you want to any functionality details of this proposed `secrets creation` tool

## List of secrets:

Secret Name | Type | Purpose | Environment | Required info from user? | If Required, more details
-- | -- | -- | -- | -- | --
storage-account-credentials | generic | credentials used for google backup storage service (e.g. database or elasticsearch) | Production Site Only | YES | account private key. In json format
smtp-secret | generic | used to (connect to SMTP service) send out data request emails | Preview, Dev & Production | YES | requires username & password for the SMTP service
db-passwords | generic | credentials used to connect to dataset (difference from `storage-account-credentials` is this info is required after you connect to database service and try to operate on a logic database) | Preview, Dev & Production | NO | This will be auto generated (if user not specified) during the deployment.
regcred | docker-registry | gitlab docker image registry credentials | Preview, Dev & Production (seems only used for re-taging for production deployment) | YES | Required info are: docker-username: always be "gitlab-ci-token" docker password: supplied by gitlab via env variable automatically `docker email`: docker user email
oauth-secrets | generic | provide signle sign-on service to google account holders or faceback account holders | Preview, Dev & Production | YES | Required info: facebook-client-secret and google-client-secret
auth-secrets | generic | internal used secrets for authentication service | Preview, Dev & Production | NO | The following info needs to be auto generated: jwt-secret, session-secret
cloudsql-instance-credentials | generic | credentials used to connect google cloud SQL (database) | Production | YES | User needs to supply: credentials.json
