### ISSUE TITLE
Bugs: Organisation search

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1415]
### Problem description
- [x] Organisations search bar needs to be inline with the 'Organisations' header
- [x] Introduce helper text for search bar
- [x] Once search is conducted, result count is missing
- [x] Once search is conducted, 'clear results' is missing
- [x] For mobile, search bar should be under the heading 'Organisations'

### Screenshot / Design / File reference
https://projects.invisionapp.com/share/EUKEL58ZCKF#/screens/301745243_organisation_Search_1

<img width="1304" alt="organisations___data_gov_au" src="https://user-images.githubusercontent.com/2201814/42494348-6183ab02-8463-11e8-9b19-317bcca0b737.png">
<img width="1308" alt="2organisations___data_gov_au" src="https://user-images.githubusercontent.com/2201814/42494414-93329078-8463-11e8-8e35-d08be78f1149.png">

**Comment by chloeleichen** [comment]
A few questions

1. a bit hard to tell but the title of org seems to be different from what we currently have for org title and dataset title
i think we need to keep them consistent
2. Is the "total" datasets under each org clickable?
3 the search box color and style is different from all other searchbox color snd style, we'll need to have a new ticket to update everything all together rather than have this one different

**Comment by tkeuneman** [comment]
We'll talk in person: 
1. That's ok, go with what we have for styling
2. Ideally, it would go to the datasets for that organisation
3. Yes, it's different and should remain so as it acts different from the other search box styles
