### ISSUE TITLE
Accessibility Testing of MAGDA

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1422]
### Accessibility Testing Results:
Issue | Fix | Reference Material
-- | -- | --
Loading pages (Dataset, Org etc.) generates an orange loading bar. | Remove. |  ![image](https://user-images.githubusercontent.com/20583588/42547763-17e98bc0-8507-11e8-8e22-16c3155931b6.png)
Lacking contrast on header links | Bold or adjust colour | ![image](https://user-images.githubusercontent.com/20583588/42548076-a08d777e-8508-11e8-836d-83d68870be76.png)
Lacking contrast on Tagline and 'Explore Data' | Align Colour to: rgba(14,0,33,0.8) | ![image](https://user-images.githubusercontent.com/20583588/42548283-bdb10b3a-8509-11e8-887d-831454986ac1.png)
Account Page -> 'Sign in' button requires contrast | Disable index.css:2404. It's colouring 'Sign in' purple instead of white. |![image](https://user-images.githubusercontent.com/20583588/42548732-f7499e46-850b-11e8-98b7-c1e550e6accc.png)
Fix alt text for frontpage images | Text should present content of image and/or function of link. Since container explains content/function; set alt-text to empty/null to remove redundancy. | ![image](https://user-images.githubusercontent.com/20583588/42549280-b430fc0a-850e-11e8-850d-16c64ace7001.png)
**EDIT:** Organisations is different to other pages | Add "Search for open data" bar but change to "Search for Organisations" | ![comp](https://user-images.githubusercontent.com/20583588/42606344-68347ca2-85c0-11e8-8c09-36ae6fe6c42a.png)

**Comment by QuadTog** [comment]
@gordjw 
The orange bar doesn't fit into the design system. While it's contrast to the background purple is a decent ~5.11 (7 would be better) and we could turn it purple to align, it only appears when loading the _Datasets_ and _Organisations_ pages (fair as they have the bulk of content) but this causes consistency issues when navigating the website. 

### Problem Reproduction:
Quickly alternate between the _Datasets_ and _Organisations_ pages and the header/footer will reset on each load. Compare that to alternating between the _About_ and _Sign in_ pages.

**Comment by tkeuneman** [comment]
@QuadTog it might be quicker if we catch up on this.

Issue | Recommendation | Reference Material
-- | -- | --
Loading pages (Dataset, Org etc.) generates an orange loading bar. | We'll be awash in a sea of purple if everything is that colour. The loading orange/red bar falls into our 'delight the customer' ethos. It doesn't get in the way and doesn't perform a crucial action, but it is a supplementary, delightful thing. |  ![image](https://user-images.githubusercontent.com/20583588/42547763-17e98bc0-8507-11e8-8e22-16c3155931b6.png)
Lacking contrast on header links | The header is a work in progress that we're trying to negotiate atm. Contrast will improve. | ![image](https://user-images.githubusercontent.com/20583588/42548076-a08d777e-8508-11e8-836d-83d68870be76.png)
Lacking contrast on Tagline and 'Explore Data' | Can you test again with this? Looks like the version you had didn't have a thick font. I'm interested in the line between readable and opacity for this. | 
![screen shot 2018-07-18 at 2 49 05 pm](https://user-images.githubusercontent.com/2201814/42860488-2bffa1a6-8a9a-11e8-8374-21ca18840596.png)
Account Page -> 'Sign in' button requires contrast | Yup. Let's do it. Disable index.css:2404. It's colouring 'Sign in' purple instead of white. |![image](https://user-images.githubusercontent.com/20583588/42548732-f7499e46-850b-11e8-98b7-c1e550e6accc.png)
Fix alt text for frontpage images | Stephen Cannings might be working on this already. Can you check with him? | ![image](https://user-images.githubusercontent.com/20583588/42549280-b430fc0a-850e-11e8-850d-16c64ace7001.png)
**EDIT:** Organisations is different to other pages | This distinct UI change was done with intent so that a user doesn't confuse the two different search functionalities. I can pretty much guarantee that if we were to do usability testing on the purple search bar performing two different functionalities, it would be confusing at best. As humans, we hardly read things at the best of times.  | ![comp](https://user-images.githubusercontent.com/20583588/42606344-68347ca2-85c0-11e8-8c09-36ae6fe6c42a.png)

Thanks for doing this! 👍

**Comment by gordjw** [comment]
I'm not sure that the contrast check applies to this - the scores usually apply to text, I don't think this would get pulled up by any tester (for this reason)

**Comment by gordjw** [comment]
@tkeuneman re: tagline and explore data - I was testing the worst case scenario (white background image behind the labels). It doesn't have to be a big change, just up the background alpha value to 0.8-0.9.

**Comment by gordjw** [comment]
There's a few other issues as well:

- No content without JS (this is a hotly debated thing that I don't expect to solve soon)
- Filters aren't keyboard navigable (using spans without any anchors)
- Search suggestions/recent keywords dropdown aren't keyboard navigable
- Focus/active colours have insufficient contrast for small text on dark backgrounds (tab through the footer to see what I mean)

I'm working on a couple of these locally, especially the filters and the focus colours.

**Comment by tkeuneman** [comment]
@gordjw Sounds good. 
Background alpha is a go at 0.8 🥇 
<img width="1191" alt="screen shot 2018-07-18 at 3 16 51 pm" src="https://user-images.githubusercontent.com/2201814/42861273-ab15c4f4-8a9d-11e8-8732-e87038f0a186.png">

I thought the recent keywords dropdown was navigable by a keyboard. 

Just share when you have something G!

**Comment by tkeuneman** [comment]
So who's responsible for all of these things? If it's not a single person, should we break them up into smaller tasks?

**Comment by stephencannings** [comment]
As home page images are not critical to understanding the alt text should be null, ie, alt="".

This means screen readers will skip over image and read out the heading.

**Comment by tkeuneman** [comment]
@QuadTog , @gordjw who wants to be the owner for this issue? Just trying to make it so we have someone responsible for this in this sprint. 

Alternatively, we can remove it from this sprint system and just let it tick along?

**Comment by aneesha09** [comment]
Gordon mentioned DGA is doing a complete accessibility test on MAGDA so closing this for now pending outcomes.
