### ISSUE TITLE
Filter by Data Quality/Last Update Feature Request

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1618]
### Feature Request
We've had some users reply with some search feedback and it's a good idea. We should look to implement these filters.

> Would be great if the search can have additional filter function. 
> 1. Search by last update of the dataset. 
> 2. Search by Quality of the data. 
> cheers.

> it would be handy to be able to sort by data quality as in the more stars or the less stars. 
> thank you
> 

### Screenshot / Design / File reference
1.) Make search results order from most recent to least recent #1073
2.) No ticket. Closest is the Tim Berners-Lee data quality discussion probs.

**Comment by kennly** [comment]
looking forward to the filter feature.

**Comment by AlexGilleran** [comment]
So there's two different things discussed here, filtering and sorting.

## Filtering
### Quality
How would you see this working? Like a dropdown with the number of stars?

### Last Update
I guess this could be like Google's thing where it has a dropdown with "in the last week", "in the last month", "in the last year" etc?

## Sorting
I'm reticent to introduce actual sorting seeing as it'll give you the classic problem where you sort by some dimension other than relevance and have to go through 5 pages of nearly completely irrelevant results that have matched on some super-common word in your query.

### Quality
This is a bit weird to me because we're already sorting by quality, it's just that a particularly relevant result can come above a higher-quality, less relevant one. I was inclined to think that it was actually too biased _towards_ quality if anything. Maybe we need to communicate this better via the UI? @philipgrimmett what do you think?

### Last Update
I think introducing a bias similar to the quality one where more recently updated datasets rise towards the top of the list is a good idea, I think introducing a full-on sort is a bit dangerous for the reasons two paragraphs above.

**Comment by AlexGilleran** [comment]
Folding this into https://github.com/magda-io/magda/issues/1761
