### ISSUE TITLE
Investigate how to make colour scheme configurable

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1640]
Required outputs:
1. Phil to have colour variables
2. Decide the best way so you can change colour scheme without changing docker image

Possibilities:
- Recompile SCSS on the fly
- Have a dynamic style sheet that overrides everything

Timeboxed to 2 days.

**Comment by t83714** [comment]
As it's a bit little overdue now, I am gonna wrap up my progress so far and create a new issue with extra time estimate (so we can decide whether we want to spend extra time on it in future).
### Progress So far
- A demo program has been created
  - The demo can work fine locally inside / outside local cloud cluster
  - However, this demo was failed to be processed through our production pipeline on gitlab due to an issue of the upstream lib (`chokidar` through `sass`) that `pancake-sass` that relies on
    - Tried to upgrade the `pancake-sass` to v2.1.0 but it seems the CSS compile result is not correct

You can checkout the latest code from branch `issue/1640`

### The demo program fucntionality (How it works)
Basically, the `web-server` pod will not simply statically send compiled CSS file back now.
Instead, it will re-compile all scss files and minify it in a particular order when it receives a requests to `/static/main.xxxx.css`.
Besides, it accepts query parameters. e.g. if you send a request
```
/static/main.xxxx.css?AU-color-foreground-action=green&AU-color-background=red
```
It will try to replace any SCSS variables named with `AU-color-foreground-action` or `AU-color-background` (with value `green` & `red`) before compile the scss files on-fly (If the variable name can't be found, it will just ignore that).

To play it, you can run the `magda-web-server` pod in your local minikube cluster (the pod might take 2~3 mins before ready as there are some scripts to be run).
Then access it either through gateway or port-forward it.
Then:
- Open the magda home page. The loading will be a bit slow and you will see a white screen for up to 30 seconds
- Once the home page is fully loaded, you can open the console and run followings to change the color (or any other CSS variable):
```
updateAppScssVars({"AU-color-foreground-action":"green", "AU-color-background":"red"})
```
After the code is run, you might see the UI losing its layout for 30 seconds while new css is loading in the background
- after the new css is fully loaded, you can find the background color has been changed.

**Comment by t83714** [comment]
Created a new issue here: #1695
