### ISSUE TITLE
Improve Dept. of Environment and Energy CSW connector behaviours

### ISSUE THREAD

**Issue by maxious** [magda-io/magda#1663]
### Problem description
Using http://www.environment.gov.au/fed/csw as a source for the CSW connector https://github.com/magda-io/magda/blob/7332fa1c74deb1fa5da28484351c2b5d79540012/deploy/helm/magda-dev.yml#L163

Records will not link correctly to source or generate distribution links https://dev.magda.io/dataset/ds-environment-%7B037B7B85-B28D-4B0C-9AE2-53D7E3E0916D%7D/details?q=

It should be possible to fix both eg. gmd:distributionInfo/gmd:MD_Distribution/gmd:distributor/gmd:MD_Distributor/gmd:distributorFormat/gmd:MD_Format will say what distribution formats are available at the link  'https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%s' % harvest_object.guid,

- Find out why this is happening
- If it's super easy to fix, just fix it
- Otherwise write up the fix into a new issue for estimation

### Acceptance Criteria
- Either a fix is made or we've figured why and written a new issue for estimation

**Comment by nahidakbar** [comment]
@maxious @AlexGilleran explanation notes:

The reason this happened is due to ISO19115. This is the standard that defines gmd:MD_Metadata schema. Having previously worked with people who sat in the standards committee for this particular standard and having worked on this standard related tools before, I'd like to say that like most of these ISO standards. this particular one is over-engineered to the point where there are several ways of describing the same piece of information.

For example, the department of environment catalogue service spits out distribution information from the perspective of distributors. This is different to what we have been seeing before where distribution information is organised in terms of transfer options. Neither option is wrong from the perspective of the standard.

I don't believe it is good investment for us to do a deep dive into the standard and figure out all possible ways of encoding the same information and put all that complexity into the connector. We can easy waste a few weeks doing that. We should do this case by case as needed.

Anyways, sending through a PR shortly that shows distribution info by taking access url and format from distributor info.

**Comment by AlexGilleran** [comment]
Looks like we've done the best we can with this - we're now able to get the formats from distributions but none of these datasets have links to the actual data (they all link to "environment.gov.au") or open licenses so they're going to be buried by the search anyway, e.g:
https://www.environment.gov.au/fed/rest/document?id=%7B3F351B18-1F65-4790-B5C5-2A759BDD4308%7D

The XML doesn't even include a working ID that we could use to build a landing page URL :(.

Closing for now 🤷‍♂️

**Comment by maxious** [comment]
Works for now, you can reuse the record id though eg.
https://www.environment.gov.au/fed/rest/document?id=%7B3F351B18-1F65-4790-B5C5-2A759BDD4308%7D ->
https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B3F351B18-1F65-4790-B5C5-2A759BDD4308%7D

It seems the system is based on https://github.com/Esri/geoportal-server so might be clues there too if this needs to be investigated in the future.

**Comment by AlexGilleran** [comment]
@maxious yeah but when we're crawling through we're getting pages at a time, e.g. http://www.environment.gov.au/fed/csw?service=CSW&version=2.0.2&request=GetRecords&constraintLanguage=FILTER&constraint_language_version=1.1.0&resultType=results&elementsetname=full&outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&typeNames=gmd%3AMD_Metadata&startPosition=201&maxRecords=100, so we only have the XML. There is an identifier in the XML but it doesn't actually match the one that you can plug into the `details.page` thing.

Right? I might be missing something super-obvious here 🤔

**Comment by maxious** [comment]
D'oh. Not super obvious, there is no ID in the outputSchema http://www.isotc211.org/2005/gmd ISO19139 but there are several IDs in the outputSchema http://www.opengis.net/cat/csw/2.0.2 OGC CSW ie. typeNames=csw:Record (In CKAN' CSW harvest, I am forced to start with the latter and request again to download the former so it made more sense)

ie. http://www.environment.gov.au/fed/csw?service=CSW&version=2.0.2&request=GetRecords&constraintLanguage=FILTER&constraint_language_version=1.1.0&resultType=results&elementsetname=full&startPosition=1&maxRecords=10

The first result is "National Heritage List Spatial Database (NHL) - public"
```
<dc:identifier scheme="urn:x-esri:specification:ServiceType:ArcIMS:Metadata:DocID">{DBB2344C-D0BE-4927-B0C5-44F9F8E1183F}</dc:identifier>
```
and the landing page is
https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid={DBB2344C-D0BE-4927-B0C5-44F9F8E1183F}

**Comment by t83714** [comment]
Just walked pass this issue while looking at the other issue & had a quick play~
FYI only:
It seems, although the two IDs doesn't match (one from `outputSchema http://www.isotc211.org/2005/gmd` crawl result and the one in @maxious 's link), both ids work well for the same url & points to the same dataset 🤷‍♂️ 
i.e.
Both link: https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B3F351B18-1F65-4790-B5C5-2A759BDD4308%7D
And 
https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B3F351B18-1F65-4790-B5C5-2A759BDD4308%7D
works and points to the same dataset.
