### ISSUE TITLE
Revise cache header for certain/all api calls

### ISSUE THREAD

**Issue by nahidakbar** [magda-io/magda#1790]
### Problem description

Had a bit of panic attack when google login was not working. Turned out my devtools with disable caching was off.

Turned out that cache header was set for whoami. This could probably be generalised to a subset of other api items. You don't want this or set any amount of cache over 1s. You'll need users doing hard refresh after login.

### Problem reproduction steps

Log in. State won't be reflected immediately without hard refreshing.

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/3362993/47117855-498fb800-d2b1-11e8-9ee6-06316b366a8a.png)

**Comment by AlexGilleran** [comment]
😬 oops!

**Comment by t83714** [comment]
Just try to provide more info on this:
I also had problems with login via DGA~ And posted my comment here: https://github.com/magda-io/magda/issues/341
However, my observation is different:
It seems when you log in to DGA at DGA website login page before attempt to login from Magda, it will always work fine. Otherwise, it never works for me.
Not sure there is any other reason could lead to this~

**Comment by t83714** [comment]
Had another play~ 
I think the cache is the cause~
Will create a PR for stopping cache for public-facing auth APIs
