### ISSUE TITLE
Exact name match not showing at the top of the search result

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1949]
### Problem description
If I type 'air passenger exams', the file with the exact match does not show at the top of the list.

### Problem reproduction steps
Involve Aneesha in making a decision if needed

### Screenshot / Design / File reference
https://trello-attachments.s3.amazonaws.com/5bfe06d0ee33aa32f1c25f82/5c12f25322b99e19dd56a97b/93bbf0d8ce902cfd71883bc0010c6a71/wrong_results_sorting.PNG

**Comment by AlexGilleran** [comment]
Sadly this is happening because when there's no quality rating aspect, we're setting the quality to `0` in elasticsearch. When elasticsearch multiplies the score together, this causes _every dataset_ to be rated as 0, which means there's no ordering at all :(.

I've done a dodgy fix and just manually set all the `quality` fields to `1` for now (will do for env too) but the proper fix is to fix the indexer so that it makes datasets have a quality rating of `1` if they've got no quality aspect.

**Comment by AlexGilleran** [comment]
Continuing in #1954
