### ISSUE TITLE
Spike - Investigate dynamic filters

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2014]
Investigate how we can create dynamic filters based on attributes in data. 
E.g. Filter by keywords should become available if tags are present in the data.

### Expected output:
Proof of concept of how it would work, taking into account the UI and search API
E.g. all the dropdowns in UI are hard-coded right now, if they were dynamic how would they be rendered

It's only expected that simple filters should work. E.g. saying "give me results where this path = this value, or this value is in the array at this path). Filtering by what's in a distribution should be investigated but it's OK if it's too hard.

### Rough Outline
- Web config has ability to set certain filters - e.g. tags. Provide what the filter should be called, where to find it in the search index
- Front-end provides this in its call to the search api
- Search API returns that as a facet (alongside date, organisation etc) with its response
- Front-end renders those options (alongside organisation etc)
- Front-end is then able to specify that as a filter (alongside organisation etc)

**Comment by t83714** [comment]
I think I am running out time on this one 😄 
Here is my findings so far:
- We probably want to simplify the facet processing logic before implement this logic. The current query involves too many aggregation on different levels --- once dynamic filters are involved, the extra complexity will make it too hard to debug and the result might not be straight forward to users. During the process, we probably can fix #2015 as well
- We might want to drop the partial match search strategy feature as well --- it works in a way like if all filters won't return any result then return all documents that meet `half` of the filters. It works automatically. Therefore, it's hard to figure out which filters are met for a document in result set. Consequently, not straight forward to reason the meaning of the facet options `hitCount` in this case as well. If we indeed want to offer `suggestion result` to users, we probably want to have a look at the alternative options that I described here: #2033 
- We might want to implement a different logic for `/api/v0/search/facets/format/options` (provided autocomplete / facet searching feature). Current logic reply on an independent index (`Public` / `Format`). Considering `term` aggregation won't work (at least accurately) for this scenario, we probably want to look at `Field Collapsing` --- I used it for organisation searching API and seems work well. However, it doesn't seem to work with nested field. Thus, filtering a field in distribution would be an issue.

I think if we want to implement this feature, give it 8 or 13 size estimate would be fair~

**Comment by t83714** [comment]
One more thing (might be a bit controversial ): 
Base on our use case, we may want to consider a different data structure to represent 1 to many (or collection) relationship.

Currently, we index dataset records and distributions are stored as a `nested` field on dataset. This might add extra complexity when we want to query anything related to the distribution (e.g. format, title etc.) and performance issues (consider when a dataset has a large number of distributions)

Alternatively, we might consider put our all our data in a flat structure:
- Index / store distribution record rather than dataset record
- Dataset, publish are normal object fields on the distribution records
- We will need to re-written our query based on `Field Collapsing`. i.e. Search `distributions` but collapse on `dataset id` to get a dataset list

Haven't try this option too much --- it seems involve a lot work but can be the solution for some of the existing issues.
