### ISSUE TITLE
SPIKE - Idea Generation for Keyword Extraction

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2036]
Investigate which applied/practical approaches are available for keyword extraction

### Expected output:
- What are some of the ways in which keywords can be extracted from metadata and data e.g. frequency, semantic analysis, etc.
- Exclude theoretical idea type approaches, pick ones having demonstrated library or practical proof of how it works
- This may be multiple approaches for different inputs e.g. one approach for generating keywords from description and a different one for generating keywords from csv file etc.

**Comment by t83714** [comment]
If no time, please just try the following demos I created. Otherwise, skip to the next comments for details.

- `retext-keywords` (https://github.com/retextjs/retext-keywords)

**Recommended Solution No.1**

Demo URL:

https://codesandbox.io/s/rl80mrqm94

-  Compromise (https://github.com/spencermountain/compromise)

**Recommended Solution No.2**

Demo URL:

Generate keywords from a url (by reading web page content):
https://codesandbox.io/s/v0kn247093

Generate location  / place names from a url (by reading web page content):
https://codesandbox.io/s/wy588vvln8


### Solutions less recommended:
- Rapid Automatic Keyword Extraction algorithm (Or RAKE) 
  - Node Rake: https://github.com/waseem18/node-rake
    - Demo urls: https://codesandbox.io/s/nk24rylzj
  - Rake-js: https://www.npmjs.com/package/rake-js
    - Demo urls: https://codesandbox.io/s/6lrln29qrr
  - Rake: https://github.com/sleepycat/rapid-automated-keyword-extraction
    - Demo urls: https://codesandbox.io/s/64200n1n7k

**Comment by t83714** [comment]
Summarise my findings as the followings:
*If no time to read, please skip to the the comment above and try the demos I made*
- Semantic folding (Machine learning):
How it works
The Cortical.io Retina performs the following operations:
1. Parses the input text.
2. Numerically encodes the meaning of the text as a semantic fingerprint.
3. Displays the semantic fingerprint as a square grid, where each blue dot on the grid contains part of the meaning of the text.
    1. Determines the importance of each term in the text:
    2. Generates a semantic fingerprint of the term.
    3. Compares the fingerprint of the term with the fingerprint of the text.
    4. Determines the overlap in meaning between the term and the text.
    5. Compares the frequency of the term in the text with the frequency of the term in the entire Retina semantic space.
This video explains this approach well:
https://www.youtube.com/watch?v=HLuRQKzYbb8
This approach probably can provide the best outcome (especially, in scientific area. e.g. use wikipedia to train the model ). However, can't find existing (on-site  i.e. non-api) solution that can be fit in web browser / nodejs environment.
It might be possible to create a solution from scratch based on google's sling project (https://github.com/google/sling). Probably not a good idea for our project (consider the time & budget)
- `retext-keywords` (https://github.com/retextjs/retext-keywords)
It firstly parses text content into NLCST (Natural Language Concrete Syntax Tree) https://github.com/syntax-tree/nlcst for further analysis. 
This mean this library actually understands the concepts of sentence, paragraph, phrases, words in natural language context. Behind the scenes, it still count the occurrence for importance. However, because of the natural language context awareness, the result would be more accurate.
A demo of the NLCST parse result:  https://wooorm.com/parse-latin/
The demo above uses `latin` parse where I created a demo uses customised `english-parser` for better result:
https://codesandbox.io/s/rl80mrqm94

- Rapid Automatic Keyword Extraction algorithm (Or RAKE)  is a domain independent keyword extraction algorithm which tries to determine key phrases in a body of text by analyzing the frequency of word appearance and its co-occurance with other words in the text.
A lot choice available in Python due to popular NLTK python package. Javascript implementations are also available:
  - node-rake: https://github.com/waseem18/node-rake
My demo: https://codesandbox.io/s/nk24rylzj
  - rake-js: https://www.npmjs.com/package/rake-js
My demo: https://codesandbox.io/s/6lrln29qrr
  - https://github.com/sleepycat/rapid-automated-keyword-extraction
My demo: https://codesandbox.io/s/64200n1n7k

- Solution based on NLP (natural-language processing) Lib: Compromise
https://github.com/spencermountain/compromise
It can not only recognise language structure (Prograph, Sentence, word, phrase ). But also can understand places, time, date etc.

I prepared two demos based on this solutions:

Generate keywords from a url (by reading web page content):
https://codesandbox.io/s/v0kn247093

Generate location  / place names from a url (by reading web page content):
https://codesandbox.io/s/wy588vvln8

@AlexGilleran You might be interested in this while look at GeoSpatial ticket

### Conclusion

Recommended No.1 `retext-keywords`
- Outbox solution & No extra work required

Recommended No.2 `Compromise`
- Powerful & flexible NLP solution & think about the potential
- Might requires some further development
- Less accurate than retext-keywords without adjustment
