### ISSUE TITLE
SPIKE: Fine-tune Fingerprinting

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2075]
### Problem description
Following from #2057.

We've identified that fingerprinting similar files is _possible_ but we need to spend some time and make sure it works well enough to be useful to users.

This will involve assembling a corpus of files from data.gov.au and testing/fine tuning the proposed hashing method such that we're reasonably sure it works on the most used files by agriculture/environment.

A lot of the format used are zip-based (everything Microsoft), so we might need to experiment a bit with whether we can unzip locally and hash that.

#### Tests
- Two CSV/Excel files where one is the original + some new rows - should resolve to being similar
- Two CSV/Excel files where one is the reverse of the other - _ideally_ should be similar but not a deal-breaker
- Two CSV/Excel files with the same columns but different data - should resolve to being different files
- Word/PDF document with some slight grammatical changes should resolve to similar
- Word/PDF document with an extra paragraph or two should resolve to similar
- Word/PDF document with the same template (headings) but different content otherwise should be not similar.

**Comment by nahidakbar** [comment]
Read #2057 for explanations for things
See [hashing.pdf](https://github.com/magda-io/magda/files/2917451/hashing.pdf) for results

Set up a better test based on acceptance criteria so that documents 1,2,3,4 are similar and 6,7,8 are similar. Ideally it should create a red diagonal with visible clusters on the diagonal.

Additional changes in the demo include only comparing text. It extracts text from xlsx, word and pdf documents and only compares those. Does a whitespace ignored case insensitive comparison.

Error is E_RMS type euclidean distance (lower the better). 

I was going to spend a lot of time on hashing algorithms but frequenct distribution seems to render pretty accurate results. The heatmap for Freq-256 looks as close to ideal as possible.
