### ISSUE TITLE
SPIKE - End to end basic "Approver" functionality

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2140]
Implement an end-to-end user role/permissions flow in Agency Magda to spike this.
Following is a criteria to make this change:
1. Currently there are two kinds of users - admin and non-admin
2. Introduce another kind of user, call this "Approver"
3. Create a user of type approver and give the permission to view draft datasets
4. Create a test page that shows draft datasets only to the "Approver user"
5. Ensure that non-admin users cannot view draft datasets unless they created it
6. If non-admin user not having draft datasets goes to the test page (in scenario 4 above) then the page shows blank and says "You don't have any draft datasets"

> Update on 4th Apr 2019: broke down to the following tasks:
Item 1: #2150 
Item 2: #2151 
Item 3: #2152 
Item 4: #2153 
Item 5: #2154 
Item 6: #2155

**Comment by AlexGilleran** [comment]
I'd be keen for this to touch search seeing how that's the biggest question mark 
👍

**Comment by t83714** [comment]
I think the following tasks are required to make it happen:
- 1> Create simple `Roles` & `Permissions` tables in Database & Make sure that information is available from Auth API `whoami` endpoint

We currently have  `admin` and `non-admin` but they are implemented as a simple `is_admin` field (with value yes / no) and can't support the third role `approver` without DB changes.

Moreover, having `Roles` & `Permissions` in database will provide the following benefits:
- We can try different access control story without modifying the code. Just update the records on those tables. It will save us a lot overhead while we are trying different ideas
- This allows us to transit from the current simple role model into a more formal access control model but still be compitible with current functionality. i.e. Make system still have two roles by default (Admins / Authenticated Users) and still keep the current default admin account for API access. 

To minimise the trouble of deployment, we should make sure when `roles` & `permission` tabls are empty, there will no impact to current functionality. 

We probbaly can leave the org unit structure to a sperate ticket if we still have concerns regarding its implementation.

We don't need a UI for this task. You can alter role & permission later via Database management tool.

> Item 1 Estimate: 5
> No blockers

- 2> OPA deployment:  Added OPA (Open Policy Agent) to our cluster with simple setup of:
  - 1 replicates 
  - delpoying policy via `ConfigMap` so we can modify the policy without re-deployment
    - configMap has 1 Mb limitation but should be suffient for our idea exploration
    - We can change it to a more stable option (i.e. serve a bundle via http endpoint) later 

> Item 2 Estimate: 5
> No blockers

- 3> OPA policy development: translate this issue access control story into Rego policy. Mainly:
  - Some infrastructure code:
    - Decode JWT and get User ID (If failed to decode, assume it's anonymous users)
    - Retrieve current User info from `Auth API / whoami` API 
  - Cover access control of draft / non-draft datasets (as per ticket story)
  - Cover access control of header items (so that a new `Drafts` tab is only available to certain users. e.g. Approver)
    - We probably will leave this demo on a separate branch without merging it into master. However, if want to, it allows us can deploy the same version to DGA without impact its functionality

> Item 3 Estimate: 8
> Blocked by item 1

- 4> Modify Search API `datasets` & `facets/*/options` endpoint to add a new `is_draft` parameter.
  - If `is_draft` = 1, search API returns only draft data
  - If `is_draft` = 0, search API returns only non-draft data
  - If `is_draft` not presents, search API returns both draft & non-draft data

> Item 4 Estimate: 5
> No Blockers

- 5> Re-use the current `Search Result Page` to create the Draft page
  - Make `Search` component accept `is_draft` property. 
  - when `is_draft` property is set to true, make sure:
    - search requests carries extra `is_draft` parameters
    - Any relevent text content should be re-written as draft datasets

> Item 5 Estimate: 3~5
> No Blockers

- 6> Make sure `<Header>` component access `OPA` and filter our header items that the current user is not allow to access.

> Item 6 Estimate: 3~5
> Blocked by Item 1, 2 & 3

**Comment by AlexGilleran** [comment]
So does 2 replace 1 or do they both run concurrently? I.e. there's roles and permissions in the db that get copied into OPA?

**Comment by aneesha09** [comment]
For validating search as the risky assumption, I would propose using a different spike before getting into this one. In this spike we can only try to implement current roles in the tool and apply it to existing search. Do you think that could be a way? @AlexGilleran  @t83714

**Comment by t83714** [comment]
@AlexGilleran 

Item 2 won't replace item 1. 
We probably need both task. 
But roles and permissions in the db won't be copied into OPA. 

OPA aims at high performance. Thus, it runs everything in memory.
Because of that, we need to carefully choose which data goes into the policy bundle.

A generic rule is only fundamental concepts & assumption that 
- Never change
- Or any changes will directly impact the implementation. e.g. operations definitions

should goes into OPA.
- Those will be:
  - [Resources definition](https://github.com/magda-io/magda/blob/issue/2101/magda-opa/opa/au/csiro/data61/magda/resources/data.json)
  - Operation Definitions (Defined in the same file above).

Other data should be stored in DB and Only the current user's portion will be supplied to OPA via:
- `input`: This is part of the `Query` request when a service needs to consult OPA regarding an Access decision
  - JWT token: we only supply JWT token to OPA. And OPA can decode user ID with it
- Once OPA receive the query, it will access the another API (Auth API / whomai) to retrieve current user info with the User id. 
  - OPA creates a HTTP request (with a User ID from JWT) to get followings from `Auth API / whomai` 
  - Current user General Info: Name, Email etc.
  - Current user's Roles
  - Current user's Permissions
  - Current user's Managing Org Units (Only IDs). We probably don't need this for this ticket

For performance consideration, we might want to put a `Redis` to cache the caculation of the current user info. But we probably don't need it in the short term.

**Comment by t83714** [comment]
> For validating search as the risky assumption, I would propose using a different spike before getting into this one. In this spike we can only try to implement current roles in the tool and apply it to existing search. Do you think that could be a way? 

@aneesha09 

I think it is `the biggest question mark` because so far there is no other access control solution provided a valid generic solution yet. And that's also the reason why most people implement their own customised for their projects (that requires data filtering) in this area.

OPA's solution is a reletively new concept and looks quite promising.

But if later we found out it's still a dead end, we probably will have to dump everything and go down to the path of customising our own access control solution...

Therefore, we probably want to verify it first. But that feature actually can't be verify without a context (story).
I think your ticket helps a lot by setting up a right size story for verifying it.

**Comment by t83714** [comment]
I think this is done (and merged) already~
