### ISSUE TITLE
SPIKE - Org Unit

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2142]
Implement a basic proof of concept to mirror agency organisation structure in agency magda
1. Have a way to have the hierarchy of agencies mapped into Magda so it can be identified as to which part of the agency a dataset is associated with. E.g.
Department -> Multiple Divisions -> Each division has multiple branches -> Each branch has multiple teams or sections
2. Associate a dataset with a team and show the corresponding upward hierarchy on a test page
3. Refer to dept structure for Ag for reference here - http://www.agriculture.gov.au/about/who-we-are/org-structure and env here - https://www.environment.gov.au/about-us/departmental-structure

**Comment by t83714** [comment]
To implement an organization structure, we need to implement a Tree structure in our storage.

- I think we can have different implementations.  e.g. We can choose put it into the registry or a separate table in auth database.
Because of the usage of this organization structure will highly likely to be `read often` & `modify less often`.

- The most common table structure is the `Adjacency List` model. 
i.e. a table with the following fields:
  - Org Unit Name
  - Parent Id

However, it's hard to traverse the tree (require more than 2 joins depends on max hierarchy levels) 

Considering the most common operation of this Tree structure is to figure out all the children nodes of a given node, this solution won't be scalable with acceptable performance.

We probably can implement it as a [Nested Set Model](https://en.wikipedia.org/wiki/Nested_set_model). i.e. the the following fields:
- Org Unit Name
- Left: the left side count from top of the tree to current node
- Right: the right side count from top of the three to current node

This allows us to figure out all children nodes with 1 joins regardless max hierarchy levels.

Updates will be a bit slower but fit our purpose as we won't modify the org chart every seconds.

Tasks required:

- 1> Complete Issue #2140 

> No estimate as it refers to another ticket

- 2> Implemented `Nested Set Model` in auth DB as a separate table. This includes
  - Setup DB strcuture
  - Complete common functions (in NodeJs in `Auth-api` module) such as: 
    - Add, Edit, Delete
    - Traverse the tree
  - Make sure current user's managing org units are available from `auth-api` `whoami` endpoint
  - Provide a new API endpoint for querying a node's direct childrens (it's for item 3)

> Item 2 Estimate: 5~8
> No Blockers

- 3> Provide a UI that display the whole org chart hierarchy on a test page 

> Item 3 Estimate: 3
> Blockers: Item 2

- 4> Modify Create Dataset logic: if the creator belongs to a org unit, assign the dataset's org unit owner to the org unit that the creator belongs to 

> Item 4 Estimate: 3
> No Blockers

- 5> Modify Indexer: Make sure the new field (org unit id) of the datset flow into elasticsearch.

> Item 5 Estimate: 3
> Blockers: Item 4

- 6> Modify OPA policy & Roles Permissions in DB accordingly to make sure:
  - All users (if they are allowed to see draft dataset), they can only see draft datasets belongs to their org units (or lower level org units) 
  - This policy rule changes should automactally be enforced in search API without code changes (as result of `Partial evaluation` implmentation in issue #2140 )

> Item 6 Estimate: 5
> Blockers: Item 1, 2, 4 & 5

@aneesha09 & @AlexGilleran please let me know your idea~

**Comment by AlexGilleran** [comment]
Refined into smaller issues - #2184 #2185 #2186 #2187 #2188. The last bit we will refine next week with a fuller team.
