### ISSUE TITLE
SPIKE - Notifications on Magda

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2219]
### Technical Investigation 
What should be the architecture of this solution that can meet the below criteria?

### Acceptance Criteria

When a user submits a dataset for approval, Magda should notify the approver on Magda and on email that they have a dataset to approve.

When a dataset is approved and published, the user that submitted it must be notified. This dataset should available in "Recently published datasets" in relevant places.

User should be potentially able to turn off email notifications or change them to digest.

The mechanism could potentially allow for other notification mechanisms to be plugged in, if needed in future.

**Comment by nahidakbar** [comment]
## Assumed Use Cases

* When a dataset is approved and published, the user that submitted it must be notified. This dataset should available in "Recently published datasets" in relevant places.
* User should be potentially able to turn off email notifications or change them to digest.
* The mechanism could potentially allow for other notification mechanisms to be plugged in, if needed in future.
* The mechanism should be able to used (in future) to receive system notifications (e.g. system down etc)

## Assumed not to be use cases

* Mass notifications/emails to all users (e.g. When marketing emails need to be sent, notify all users)

## Idea

I think we should consolidate external communications into a service.

![image](https://user-images.githubusercontent.com/3362993/58442269-f0ccab80-812c-11e9-9d9f-931842597c8f.png)

**Comment by AlexGilleran** [comment]
I like the first option :). I like the idea of keeping Correspondence separate to Notifications/Subscriptions though - i.e. there's a Notification microservice that knows all about who needs to know about what when, then a stateless correspondence service that only knows how to send various types of correspondence instantly (including email, sms, push notifications etc).

I think ideally for managing the queueing we'd get https://github.com/magda-io/magda/issues/796 done, although we might have to end up doing this then that, not sure what the best interim solution is.

@t83714 thoughts?

**Comment by t83714** [comment]
I like the idea of reuse our event sourcing mode~
However, as @nahidakbar suggests, we will need to have a the workflow / logic on when to trigger notification.
It could be simple or hard --- for complicated scenario, a notification could need to be triggered only after a series events in particular order --- like a transaction in DB
 
The other thing I think we might want to think over is how to determine potential subscribers for a given topic. Surely, users are allowed to cancel the notifications or turn it back on. 
But when it comes to a particular notification (let's say when we now need to send notifications to relevant approvers for a publishing request), we will need the logic to determine a list of persons who should potentially be a subscriber. 

e.g. A user may decide to receive notifications for topic of `approval request`. It doesn't mean he will receive all approval request notifications generated from system but only those he has permission to approve. --- the actual logic could vary depends on notification topic

This logic should be additional to the `Subscriptions` layer. We may decide to include this logic in our notification system or make it simple so that the notification system just get fed with a list of users plus notification message content (i.e. focus on delivery).

If we decide to cover this part in this notification system and keep it generic, I feel like that could be another area where we might need to leverage the `partially eval` capability 😄

**Comment by AlexGilleran** [comment]
Following up in https://github.com/magda-io/magda/issues/2352
