### ISSUE TITLE
Spike: Figure out how a "Deploy Magda" button could work

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2488]
## Description
This is the first step of making a "Deploy Magda" button - figuring out how we do it.

## What we need to find out
- What's the quickest way we can make this happen? (presumably https://cloud.google.com/blog/products/gcp/automating-project-creation-with-google-cloud-deployment-manager)
- What will the resulting user journey look like?
- Is it worth the effort for us to do?

**Comment by t83714** [comment]
My conclusion:

#### Summary

Yes, it's possible. It can be:
- Fully automated
- Without any manual help from the user

The user only needs to log in his google account (if he hasn't) and agree to give us the permission to a list of security scopes (will be shown on google's login screen).

For the user journey, please see below.

It probably requires a week to create a prototype (i.e. user won't be offered any config options. Deployment config are hardcoded).

I think if we want to differentiate Magda (as an open-source solution from ) from Ckan as revolutionary easy to deploy cloud solution. This `one-click` feature can work as proof.
Besides, if we take action now, we likely have the chance to complete a prototype by 1st Oct --- We probably can let people have a try on data61 live.

#### More details

1> Deployment Manager doesn't fit our purpose because:
- To deploy using `Deployment Manager`, you need something like: `gcloud deployment-manager deployments create ${NAME}     --template cluster.py     --properties zone:${ZONE}` (or talk to deployment API (quite like tiler) directly)
  - Before that, you need to 
    - Create a project & fix billing account
    - complete auth for gcloud, and enable
- It requires authentication through `gcloud`. 
  - Maybe it's possible (with knowledge of google's hidden API) --- but I can't find a way of SSO (for gcloud) without user's help (e.g. enter verification code)
- deployment API works at project level do not have enough authorisation to achieve certain tasks on behalf of users. 

2> Alternatively, a feasible solution could be talking to various google APIs directly (using [Google Api lib](https://github.com/google/google-api-javascript-client)).
I've verified the whole journey by manually sending requests to APIs. Here are the details:
- Once the user clicks the button, our UI will open a popup and redirect to the google login page for OAuth SSO.
- User will see the list of access scope we requested.
- Once user click agree, we will first create a project (via resource manager API)
- Link an existing billing account to this project (via resource manager API)
- Enable Kubernetes API (via service manager) 
- Create a cluster (with appropriate node pool) through (via Kubernetes API)
- Create a new key for the default service account (via IAM API)
  - You get service account access key from the response. 
- Create / Reserve a Static IP via Computer Engine API
  - Lookup for any unused external ip first only create if can't find
- create a new k8s job (requires a pre-built docker image) 
  - With the following software installed
    - `gcloud`
    - `kubectl`
    - `helm`
  - with the following parameters
    -  the default service account access key (this service account has cluster-admin permission)
    - Cluster name
    - project name
    - zone or region name
    - reserved static ip
  - complete the following tasks
    - `cat ACCESS_KEY | base64 -D > access-key-file.json`
    - `gcloud auth  activate-service-account --key-file=access-key-file.json`
    - `gcloud container clusters get-credentials [cluster name] --zone [zone or region name] --project [project name]`
      - This will create the correct `kubeconfig` file and allow us to access the cluster through `kubectl`
      - git clone Magda
      - following the standard procedure to deploy Magda through `helm`
        - Use [xip](http://xip.io/) for external domain
          - the external domain will be `[static ip].xip.io` 
        - Use Google-managed SSL certificates to setup SSL

#### User Journey

![image](https://user-images.githubusercontent.com/674387/65293437-9b664f80-db9e-11e9-90ce-90b7b32ef065.png)

**Comment by t83714** [comment]
Break down tasks:
1> A docker image which can complete the deployment (as a k8s job) 
- It will accept the following parameters (pass through as env vars):
  - the default service account access key (this service account has cluster-admin permission)
  - Cluster name
  - project name
  - zone or region name
  - reserved static IP
- It will output log in the specific format to indicate the success or failure outcome (probably use [helm notes](https://github.com/helm/helm/blob/master/docs/chart_template_guide/notes_files.md)) 

2> A node-js backend:
- is capable of the followings:
  - Serve static frontend code
  - Help oauth2 processing
  - Launch k8s deployment job (as item 1) and proxy the job execution output

3> A react frontend:

- is capable of the followings:
  - Handle oauth to google acc
  -  talks to google APIs and complete the followings:
     - create a project (link billing acc)
     - create a cluster
     - reserved static IP
     - create a service account access key
  - Create deployment k8s job (via nodejs backend) and coordinate the whole deployment process

**Comment by t83714** [comment]
The [Terraform](https://www.terraform.io/docs/cli-index.html) seems can combine the usage of `helm`, `kubectl` & `gcloud`.
Will do more investigation to see if it provides a better story~

**Comment by t83714** [comment]
Terraform as a Library
https://github.com/hashicorp/terraform/issues/12582
This ticket shows Terraform doesn't have a plan (or technical reason why) to create API (rather than recommend cmd interface for API usage).

**Comment by AlexGilleran** [comment]
Spike has been spoke.
