### ISSUE TITLE
Order of query params affects results in a dataset search request

### ISSUE THREAD

**Issue by scottlimmer** [magda-io/magda#2513]
**Describe the bug**
The order of params in a request to search datasets affects the results datasets returned.

Possibly related #2512 

**To Reproduce**
E.g.: 
[https://search.data.gov.au/api/v0/search/datasets?start=20&limit=20&publisher=City+of+Ballarat](https://search.data.gov.au/api/v0/search/datasets?start=20&limit=20&publisher=City+of+Ballarat)
[https://search.data.gov.au/api/v0/search/datasets?publisher=City+of+Ballarat&start=20&limit=20](https://search.data.gov.au/api/v0/search/datasets?publisher=City+of+Ballarat&start=20&limit=20)

**Comment by AlexGilleran** [comment]
Even if you don't change around the order of the params it still changes the order sometimes, because everything is the same score (they're all City of Ballarat datasets) 😬 .

So yeah I'd say this is the same underlying cause/solution as #2512, I'll close this in favour of that one.

@scottlimmer If you're paging through in order to get the data out you might be better off using the registry API (e.g. https://data.gov.au/api/v0/registry/records?aspect=dcat-dataset-strings&aspect=dataset-distributions&dereference=true&limit=20&aspectQuery=dataset-publisher.publisher:org-dga-4e704c39-2385-42e9-a7d1-5af343c358b5), which'll give you access to more data and also won't be subject to some of the limitations of paging through elasticsearch (e.g. the query getting slower and slower as you page further and further and a hard limit of paging further than 10000 documents in) :).

**Comment by scottlimmer** [comment]
@AlexGilleran Thanks Alex, I wanted to use the registry API, it just wasn't clear to me how I would filter by publisher.
