### ISSUE TITLE
Requesting records on tenant id -1 results in an empty response

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2517]
**Describe the bug**
Currently if a reindex is requested/automatically happens in the indexer, it'll end up wiping every record out of the search index.

After some ~messing about~ investigation, turns out that this is because the requester requests records from tenant id -1. This _should_ result in all records being returned regardless of tenant, however it results in no records being returned - exactly the same as if the registry was completely empty.

**To Reproduce**
Do a request to `v0/records` on the registry API with `X-Magda-Tenant-Id` set to `-1`. You can confirm that it's not working if doing the same request with tenant id `0` actually returns stuff.

**Expected behavior**
All records on all tenants should be returned.

**Comment by mwu2018** [comment]
This bug has been addressed in PR #2495 . Please see the PR description.

**Comment by AlexGilleran** [comment]
hi @mwu2018 - do you mean #2508 ? I'm not sure that's going to fix it - the reason that it's coming back with 0 records is because `WHERE tenantid = -1` is making it into the SQL.

**Comment by mwu2018** [comment]
@AlexGilleran Sorry it should have been PR #2508.
Aaccess control is enabled by default. Because all of records have no `dataset-access-control` aspect, all records are for public access (tenantId = 0). When reindexing, the request tenantId = -1 with admin role credentials. The opa policy will let it see all records, regardless what tenantId is.
