### ISSUE TITLE
Improve Cacheability

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2545]
## Description

Since the last time we deployed to data.gov.au we've made a few significant changes that affect the cacheability of resources on both CDNs and browsers. This is fine for _other_ instances but data.gov.au is a pretty high traffic site where users like things to be snappy! So it'd be good if we could figure out some way that the data.gov.au use case (non-logged-in-users getting completely public data) could continue to be cached.

### Background

The way that the gateway applies authentication is pretty naive - services are either authenticated or not authenticated. Previously the search api and the read-only registry were _not_ authenticated because there was no auth mechanism, but now that there is, every response that comes back from them will have a `Set-Cookie` header on it - I'm not sure how this affects cacheability in browsers, but from what I understand that will cause the Google CDN to simply avoid caching it altogether.

I believe this also affects the content-api even now - it'd be _really_ nice to have that cacheable too.

### Potential Solutions

I'm not entirely sure what the solution is here, but it might look something like:

User request comes in:
- Did they send a session id cookie? If so then send them through the current authenticated path which causes Set-Cookie to be set on the response
- Did they send no authentication cookie?
    - Are they trying to log in? In that case direct them along the current authenticated path
    - Are they trying any other service? In that case route it through to the API without a user id header attached, and DON'T set `Set-Cookie` on the response

### Acceptance Criteria

This is a spike - to close this ticket we need a plan for a solution that:
- Allows all existing logged-in functionality to work as normal, WITHOUT being cached in any CDN
- Allows non-authenticated requests to _at least_ the Search API, Registry API and Content API to be fulfilled without having a cookie set on the response
    - We should be able to say with a reasonable degree of confidence that these won't be cached by Google CDN, but if testing it is hard we can base this confidence off what the docs say for now and test it in a later issue
- Avoids express-session doing any work for unauthenticated requests - especially avoiding the pitfall where not setting Set-Cookie on responses results in a new session getting created for every individual request

**Comment by t83714** [comment]
Some ideas for comments:

- Only set session cookie to response header for API endpoint starts with `auth/login` when there is no session cookie on incoming requests
  - Currently, express-session will set a session cookie (start the session) for all `auth` && `api` routes
- Only delete the session cookie (set life to 0 on response header) when:
  - a request received for `auth/logout`
  - `/sign-in-redirect` route receive a `&result=failure` parameter

Those two rules above are in place to ensure:
- user request won't carry a cookie in the header unless they are logged in
- system won't keep creating new sessions for the same user

Problem: 
`express-session` can't be configured to implement the behaviour above.
i.e. as long as `express-session`  is on the middleware list, it will set the cookie (start the session) even we don't need.

By quick reading the source code, A hack to stop this could be setting the `req.session` to a not null value before `express-session` starts to process the request.

**Comment by AlexGilleran** [comment]
Possibly we could implement our own cookie handling logic while reusing the rest of express session 🤔

**Comment by t83714** [comment]
The [PR](https://github.com/magda-io/magda/pull/2572) has fixed the unnecessary session & cookie header issue but our frontend still request /dataset (search API) with `cache-control: no-cache` header.
The gateway will not add `cache header` in this situation as the request specified `no-cache`.

Based on Google's CDN document, CDN will only cache items if ALL of following are `true`:
- It was served by a backend service or backend bucket with Cloud CDN enabled.
- It is a response to a GET request.
- Its status code is 200, 203, 206, 300, 301, 302, 307, or 410.
- It has a Cache-Control: public header.
- It has a Cache-Control: s-maxage, Cache-Control: max-age, or Expires header.
- It has a Content-Length, Content-Range, or Transfer-Encoding header.
- Its size is less than or equal to the maximum size.

We probably want to re-visit the frontend to implement more complicated logic (for determining Cache Header in request). e.g.:
-   Always add `no-cache` to all auth related requests
-   Always add  `no-cache` to all requests after user is logged-in
-   Otherwise, add appropriate cache header to requests. e.g. `Cache-Control: public, max-age=60`

@AlexGilleran Your thoughts?
