### ISSUE TITLE
Issues when manually typing dates

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2564]
**Describe the bug**
From Rodrigo - "Date fields – I’ve encountered issues when typing a year manually – the field displays ‘invalid date’ and as soon as I click on the calendar icon to fix it, it kicks me out and all my progress is lost."

<img width="680" alt="image" src="https://user-images.githubusercontent.com/900555/67728005-ab940900-fa3f-11e9-8a80-3196e2e81939.png">

Essentially we need to try typing in dates directly into datepicker fields and fix any of the weird behaviour that results.

## To reproduce
- To get "Invalid Date": type in the text field attached to a date picker
- To get a blank screen: do the above, then click outside the date picker to dismiss it, then click the calendar icon to re-open the date picker.

## Expected Behaviour
- You should be able to type any valid date in any date picker field.
- If you type an invalid date, then it's fine for it to say invalid date
- Invalid dates shouldn't be allowed to be set

**Comment by t83714** [comment]
PR https://github.com/magda-io/magda/pull/2577 has fixed the blank screen issue and make manual type date possible.
Although we still have the `revert back to the last date` issue (see my last comment on PR page or #2585)
This issue seems triggered internally from lib `react-dates` (a bug). Thus, we probably want to handle it as a separate issue via #2585.
