### ISSUE TITLE
Figure out how other developers can use our typescript libraries

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2592]
## Description
Right now the Terria guys want to develop their own magda components, outside our monorepo, which makes sense - we don't want the entire ecosystem to live in forks.

However, there's shared typescript (typescript-common, minion-framework) that would really help, but they can't get access to it without being in the monorepo.

So we need to not only help them, but also figure out what the ideal path for someone developing magda extensions in typescript is and document.

One way that we could nearly achieve what we want is just shipping these modules to npm, which would allow them to be `npm install` ed. But it's possible that someone might want to make a change to the module while using it. This would require them to git clone the entire monorepo... which might be ok using `npm link` but won't work (or maybe will?) with [yarn workspaces](https://docs.terria.io/guide/contributing/development-environment/).

Possibly we could break these modules out into their own modules but then we'd lose the advantages of a monorepo. 

So essentially, we need to figure out the best way to develop typescript magda components, make any changes necessary to our code to make it work, and document it.

**Comment by t83714** [comment]
Just food for thought:

I think from a minor / connector developer’s point of view, he probably cares about less how we organise repo and wants us to release a list of independent NPM packages with different topics (instead of one single `typescript-common` package).

He might want:
- Registry Client: any functionalities related to talking to a Magda registry APIs
- Connector Lib: 
  - Depends on `Registry Client` lib
  - Common code & based class that use to build a connector. e.g.:
    - `JsonTransformer`, `JsonConnector` etc.
- Minor Lib:
  - Depends on `Registry Client` lib
  - Common code & based class that use to build a minor. (e.g. minor-framework)

**Comment by AlexGilleran** [comment]
Closing in favour of #2628
