### ISSUE TITLE
Re-order drop downs in people and production

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#2595]
## Description

Swap the order of "team responsible for maintaining", and "area referenced as data custodian" in people and production.

Swap the order of the radio buttons under "How should the contact point(s) be referenced in the metadata?" as per the above.

## Acceptance Criteria

-   The drop downs appear in the order of "referenced as the data custodian" and then "team responsible for maintaining".
- When selecting custodian, bring branches under custodian to the top (but do not filter list)
- When selecting "how should the contact point be referenced in the metadata" the radio buttons should be in the order of 1) maintaining team, 2) organisation name, 3) data custodian area name.

## Technical Notes

![image](https://user-images.githubusercontent.com/38118717/68734159-6cfc7200-062d-11ea-94d7-04e37e30f8a3.png)

For the radio buttons:

![image](https://user-images.githubusercontent.com/38118717/68734748-90282100-062f-11ea-83aa-04e388dc6c3c.png)

**Comment by t83714** [comment]
@sajidanower23 
Have to say when you ask me about this originally, I also didn't read the ticket carefully.
The requirements are included in the `Acceptance Criteria`:
> When selecting custodian, bring branches under custodian to the top (but do not filter list)
So when the user selects an option for `Which area of the organisation should be referenced as the data custodian?`
The dropdown options of the question `team responsible for maintaining` should be re-ordered so that all teams within the same branch of the selected custodian (i.e. the `relationship` field of the api response should be`descendant`) should be shown on top of the dropdown.
