### ISSUE TITLE
Error notification no longer has a white background

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2805]
**Describe the bug**
The existing error notification now has an invisible background:

![image](https://user-images.githubusercontent.com/900555/79516763-a7ac7f80-808f-11ea-9ea0-454dc4ef1589.png)

**To Reproduce**
1. Go to the search page (e.g. dev.magda.io/search).
2. Do something to disable the search request (e.g. Firefox has Request Blocking, you can block anything with "datasets" in it).
3. Search for anything.

**Expected behavior**
The notification should have a white background,  like it does in the last version on data.gov.au:

![image](https://user-images.githubusercontent.com/900555/79516814-d3c80080-808f-11ea-84fd-45abb230e14b.png)

**Desktop (please complete the following information):**

-   OS: Arch Linux (btw)
-   Browser: Firefox
-   Version: 74

**Additional context**
- This is possibly because we upgraded the dta design systems and had a CSS customisation that no longer works?
- It might also not occur when running `yarn run dev`, you might need to compile the CSS with `magda-scss-compiler` to see it.

**Comment by t83714** [comment]
Came across this while debugging other CSS issues.
It looks like a simply issue that `au-body` class is missing at line:
https://github.com/magda-io/magda/blob/0955ca614ddb4704dffcb72b9850d97e384e0898/magda-web-client/src/Components/Common/Notification.js#L28
See au/gov component doc:
https://designsystem.gov.au/components/page-alerts/

By the way, the way of `magda-scss-compiler` compiling scss/css is consistent with `yarn build` (build version).
It's `yarn dev` does it in a little different way due to hot loading.

**Comment by t83714** [comment]
Fixed by PR https://github.com/magda-io/magda/pull/2845 & merged
