### ISSUE TITLE
Add an auth mechanism for direct API consumers

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2883]
## Description
Currently in order to authenticate when using the API, you need to send your cookie, which you get by authenticating through the web app.

Obviously this isn't much use if you're building an app to directly consume the API.

We need to figure out the best way to make this happen, with reference to best practice and our existing auth setup.

Potentially this could be an API key (like CKAN and many others), although if there's some better way it could be that too.

### Acceptance Criteria
- Look up various ways that APIs are authenticated now to get an idea of the state of things
- Write up some of the alternatives (briefly) with pros and cons, especially with reference to 
    - How easy it will be to fit into our existing authentication mechanism
    - How easy it is to allow/deny access
- Simple is better than complex, ideally

**Comment by sajidanower23** [comment]
Here's my thoughts on it:

# User access to Magda API

API keys are perhaps the simplest way of doing this.

Good article: <https://www.freecodecamp.org/news/best-practices-for-building-api-keys-97c26eabfea9>

## Structure of the key

Note that API keys need to be hashed and salted before being stored in the database

Name - string
Hash (salted) - string
Scopes - Array of strings

### Scopes

Scopes can be named however you like, but following a convention makes it easy
for every one to use the scopes programatically.

One possible convention to name the scopes is `service.action`.

Some possible scopes:

Storage

```txt
storage.all
storage.upload
storage.download
storage.delete

Registry
registry.download

User
user.read
user.write

Search
search.results
```

## Rate Limiting

Rate limiting is important to prevent the abuse of our API, since API keys are
being provided for free.

Express has a library [https://www.npmjs.com/package/express-rate-limit](express-rate-limit)
that can be used to rate-limit endpoints as express middleware.

Code for that would look like this:


```javascript
import rateLimit from 'express-rate-limit';

export const rateLimiter = rateLimit({
  windowMs: 60 * 1000, // 1 minute, in milliseconds
  max: 1000,
  message: 'You have exceeded the API rate limit',
  headers: true,
});

router.get('/endpoint', rateLimiter, function(req, res) {
    return "Woah";
})

```

This will result in denial of requests if the limit is exceeded.

To go into more depth, check out these articles:

<https://nordicapis.com/everything-you-need-to-know-about-api-rate-limiting>

<https://blog.logrocket.com/rate-limiting-node-js>

**Comment by AlexGilleran** [comment]
- Use API Keys
- How to rotate/invalidate keys?
    - Create new one, delete old one
- Scopes?
    - Don't worry about being able to assign scopes to API keys yet, for now the preferred approach to fine-grained permissions via the API is to generate a service account with the correct permissions and let the general authorisation system handle it
    - At some point we might want to be able to do this for a use case where you want to generate a key that e.g. only has access to read records but not your user information, similar to how oauth does it
- Rate limiting
    - Another issue
    - Should probably be disable-able for simple / small / internal instances, would be _awesome_ on data.gov.au though
    - Will need to centralise where the data around rate limiting is stored in case we have multiple gateway instances - possibly using https://www.npmjs.com/package/rate-limiter-flexible and postgres

**Comment by AlexGilleran** [comment]
Closing the spike, work will continue in #2897
