### ISSUE TITLE
Script create-api-key.js can't connect to pod combined-db-0

### ISSUE THREAD

**Issue by Docteur-RS** [magda-io/magda#3049]
**Describe the bug**
Script `create-api-key.js` fails with error `Error: Connection terminated unexpectedly`

**To Reproduce**
Following the documentation at [how-to-create-api-key](https://magda.io/docs/how-to-create-api-key)

* 1) `yarn install` => **OK**

* 2) `kubectl port-forward combined-db-0 5432:5432` => **FAIL**
```
unable to create listener: Error listen tcp4 127.0.0.1:5432: bind: permission denied
```
The port 5432 can't be assigned instead I had to port foward on 8080 like this : `kubectl port-forward combined-db-0 8080:5432`

* 3) Setting some stuff:
```
export POSTGRES_HOST=127.0.0.1:8080
export POSTGRES_PASSWORD=xxxxxxx (got from secret in magda namespace)
```
* 4) `yarn create-api-key -l`   => **FAIL**
`Error: getaddrinfo ENOTFOUND http://127.0.0.1:8080`  
I had to edit *node_modules/pg/lib/defaults.js* to update the port definition to 8080.

* 5) `yarn create-api-key -l`  => **FAIL**
```
...(waiting)...
Error: Connection terminated unexpectedly
```

**Expected behavior**
Connection to pod combined-db-0 should work and list users

**Desktop (please complete the following information):**
WSL: Ubuntu 16.04
Magda version : 0.0.57

**Comment by Docteur-RS** [comment]
The port-forward issue on 5432 seems to be related to my computer. But it doesn't change the fact that connection to pod combined-db-0 is being terminated.

**Comment by t83714** [comment]
@Docteur-RS 
The port-forward on 5432 issue seems a combination of windows permission & firewall issues (the `Connection terminated unexpectedly` might be caused by the firewall issue).

See [here](https://github.com/microsoft/WSL/issues/4406) and [here](https://github.com/microsoft/WSL/issues/4106)

Can you try:
- run kubectl with `sudo` 
- turn off the firewall of your local computer (or add a rule for`kubectl`)

You can verify the DB connection using other DB admin tool. e.g.: https://www.pgadmin.org/

The `POSTGRES_HOST` var is only for hostname (or IP address part) and I don't think you can include "port" info there.
If you really want to use a different port, you can edit https://github.com/magda-https://github.com/magda-io/magda/blob/c167319baf1dda104b9318e4caf050c0960aaa0a/scripts/db/getDBConfig.js#L13
Instead.
Just simply add a new field `port` with a different value.
e.g.:
```typescript
return {
        host: host ? host : "localhost",
        database: database ? database : "auth",
        user: user ? user : "postgres",
        password: password ? password : "",
        port: 8000
    };
```

**Comment by Docteur-RS** [comment]
@t83714 Thank's for your answer.

I added the "port" field like you did and its working ! Thx
