### ISSUE TITLE
Search Filters: Why show publishers with 0 search results?

### ISSUE THREAD

**Issue by sukhrajghuman** [magda-io/magda#858]
### Problem description

If I make a search query and I try to filter by publisher, it shows publishers that have no search results for that particular search query. 

Often these publishers who have 0 search results are shown above publishers who actually have search results

### Problem reproduction steps
See Screens below

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/20184809/39171943-99afb9d8-47e3-11e8-8278-d26e3a74c32d.png)

<br/>
<br/>
<hr/>
<br/>
<br/>

![image](https://user-images.githubusercontent.com/20184809/39171987-b5d625de-47e3-11e8-9353-01ea507216f2.png)

**Comment by AlexGilleran** [comment]
It's controversial - the original reason is that we wanted to make it so that if you searched for a publisher that didn't have any results, you'd know that yes, you typed the publisher correctly and it exists in the system, but it doesn't have any results for this particular query.

We could revisit it though.

**Comment by sukhrajghuman** [comment]
Maybe we could have it that the publishers with results show up higher than the publishers with no results?

**Comment by AlexGilleran** [comment]
Done now :).
