### ISSUE TITLE
Background link on home page causes a whole page reload

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#882]
### Problem description
If you click on the link that goes with the background... e.g.

![image](https://user-images.githubusercontent.com/900555/39347578-dc0aeda2-4a36-11e8-94de-9673fdb8c64e.png)

It isn't using a react-router `<Link>` component, so it forces an entire page refresh rather than just shifting routes.

We should make it use a `<Link>`

**Comment by ketikat** [comment]
Hi working on this issue now. Stay tuned for PR.

**Comment by adamzerella** [comment]
Nah, it's in the top right corner of all issues:

<img width="1018" alt="screen shot 2018-04-30 at 10 42 58 am" src="https://user-images.githubusercontent.com/1501560/39412682-8c87d914-4c63-11e8-9982-96295e4ecb3e.png">

**Comment by ketikat** [comment]
right, mine is greyed out though. I think it's because I didn't add myself to the list of contributors? Sorry to drag this out, maybe I'm missing something. 

<img width="396" alt="screen shot 2018-04-29 at 9 10 00 pm" src="https://user-images.githubusercontent.com/30533440/39412967-b1baa738-4bf1-11e8-847a-13c86717c041.png">

**Comment by adamzerella** [comment]
@steve9164 @ketikat Ahh, my mistake. Sorry guys
